name = "Simply Infinite"
author = "ConGodsted"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "682f3e993ca0e1f086c5e5a6c9cbc79ce2a1abecbb64b0dd5026c4e0cf6e826c"

[versions]
fabric = "0.11.7"
minecraft = "20w14infinite"

[options]
acceptable-game-versions = ["1.16.2"]
