name = "Simply Infinite"
author = "ConGodsted"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1b11a34cb39ff5c6b889cec9a25965f071dcf55c3331ee0df46414c44c81e03"

[versions]
fabric = "0.11.7"
minecraft = "20w14infinite"

[options]
acceptable-game-versions = ["1.16.2"]
