name = "Simply Infinite"
author = "ConGodsted"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b781cff17434aec1122aaeca5d110c8dc8c0284fc13e015f4c312c6b5c740ea"

[versions]
fabric = "0.14.23"
minecraft = "20w14infinite"

[options]
acceptable-game-versions = ["1.16.2"]
